"""The grid runner: methods x datasets x modes -> tidy CSV.

Two modes, run separately because they answer different questions (see
``metrics.precision``):

* ``tolerance`` -- every method gets the same ``delta`` and reports the ``R`` it needed.
  NMF and POD cannot enter: [BEE20] §5's objection to NMF is precisely that "the user
  does not specify an error tolerance but only the cardinality".
* ``cardinality`` -- every method gets the same ``R``. The only mode where the baselines
  are comparable at all, and the one on which [BEE20]'s notes record NMF beating CPG.

By default only ``adapters.DEFAULT_METHODS`` runs: one canonical implementation per
algorithm. The duplicate transcriptions stay reachable via ``--methods``, and
``agreement.csv`` is built from ``CROSS_FAMILY_PAIRS`` regardless, so the
cross-implementation check keeps running even when they are not in the grid.

**Skips are recorded, not silently dropped.** Every cell that does not run emits a row
with a ``skip_reason``, because "this method was not measured here" and "this method
scored badly here" must never be confusable in the output. The three legitimate skip
causes are: a method that does not support the mode, a dataset that cannot supply an
inf-sup input, and a genuine failure (recorded with its exception).

Long-running cells are the norm -- ``hertz_pressure`` has 4000 snapshots and each
selection sweep is one NNLS per snapshot per iteration -- so ``--subsample`` caps the
training set for exploratory runs. It changes the numbers and is recorded in the output.
"""

from __future__ import annotations

import argparse
import csv
import dataclasses
import json
import platform
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from . import _paths, datasets as ds_mod, metrics
from .adapters import CROSS_FAMILY_PAIRS, DEFAULT_METHODS, METHODS
from .types import Dataset

RESULTS = _paths.ROOT / "results"

# The tolerance grid has to span two orders of magnitude because the datasets differ
# enormously in how compressible they are. `gaussian_synth` still needs R = 15 at
# delta = 0.1, while `fem_lambda` and `physics` are near-rank-1 (s1/s0 = 0.026 and
# 0.057) and saturate at R = 1 there -- a cone of one generator, on which every
# conditioning metric is degenerate. Without the tight end of this grid those two
# datasets contribute no informative row at all.
DEFAULT_DELTAS = (0.5, 0.2, 0.1, 0.05, 0.02, 0.01)
DEFAULT_CARDINALITIES = (4, 8, 12, 16)


def _subsample(dataset: Dataset, cap: int | None) -> Dataset:
    """Cap the training set, keeping the split structure intact.

    Takes an evenly spaced stride rather than the first ``cap`` columns: several
    sources are generated by sweeping a parameter monotonically, so a prefix would be a
    narrow slice of parameter space and would understate every method's ``R``.
    """
    if cap is None or dataset.n_snapshots <= cap:
        return dataset
    idx = np.unique(np.linspace(0, dataset.n_snapshots - 1, cap).astype(int))
    keep = set(int(i) for i in idx)
    remap = {old: new for new, old in enumerate(sorted(keep))}

    def project(sel):
        if sel is None:
            return None
        out = [remap[int(i)] for i in sel if int(i) in remap]
        return np.asarray(out, int) if out else None

    fields = dataclasses.asdict(dataset)
    fields["snapshots"] = dataset.snapshots[:, sorted(keep)]
    fields["params"] = dataset.params[sorted(keep)] if dataset.params is not None else None
    fields["primal_snapshots"] = (dataset.primal_snapshots[:, sorted(keep)]
                                  if dataset.primal_snapshots is not None else None)
    fields["train_idx"] = project(dataset.train_idx)
    fields["test_idx"] = project(dataset.test_idx)
    fields["name"] = f"{dataset.name}[n<={cap}]"
    # dataclasses.asdict does not round-trip callables; carry B_of_mu explicitly,
    # re-indexed onto the retained columns.
    order = sorted(keep)
    original_B = dataset.B_of_mu
    fields["B_of_mu"] = (None if original_B is None
                         else (lambda j, o=order, f=original_B: f(o[j])))
    fields["A"] = dataset.A
    return Dataset(**fields)


def run_cell(dataset: Dataset, method_key: str, *, delta=None, R=None,
             with_infsup: bool = True, with_determinism: bool = True) -> dict:
    """One (dataset, method, setting) cell: fit, then all applicable metrics."""
    method = METHODS[method_key]
    row: dict[str, object] = {
        "dataset": dataset.name,
        "method": method_key,
        "method_label": method.label,
        "family": method.family,
        "paper_tag": method.paper_tag or "-",
        "mode": "tolerance" if R is None else "cardinality",
        "delta": delta if delta is not None else "",
        "R_requested": R if R is not None else "",
        "dim": dataset.dim,
        "n_train": dataset.train().shape[1],
        "skip_reason": "",
    }

    if R is None and not method.supports_tolerance:
        row["skip_reason"] = method.tolerance_note
        return row

    try:
        result = method.fit(dataset, delta=delta, R=R)
    except Exception as exc:                      # noqa: BLE001 -- recorded, not hidden
        row["skip_reason"] = f"fit failed: {type(exc).__name__}: {exc}"
        return row

    if result.R == 0:
        row["skip_reason"] = "empty cone (no generator met the tolerance)"
        return row

    try:
        row.update(metrics.precision.evaluate(dataset, result))
        row.update(metrics.performance.evaluate(dataset, result))
        row.update(metrics.cone_geometry.evaluate(dataset, result))
        row.update(metrics.stability.evaluate(
            dataset, result, with_infsup=with_infsup and dataset.supports_infsup))
        if with_determinism:
            row.update(metrics.stability.determinism(method, dataset, delta=delta, R=R))
    except Exception as exc:                      # noqa: BLE001
        row["skip_reason"] = f"metric failed: {type(exc).__name__}: {exc}"

    row["notes"] = result.notes
    return row


def run_agreement(dataset: Dataset, *, delta: float) -> list[dict]:
    """Cross-family comparisons at one tolerance."""
    rows = []
    cache: dict[str, object] = {}
    for a_key, b_key in CROSS_FAMILY_PAIRS:
        row: dict[str, object] = {
            "dataset": dataset.name, "pair": f"{a_key} vs {b_key}",
            "method_a": a_key, "method_b": b_key, "delta": delta, "skip_reason": "",
        }
        try:
            for key in (a_key, b_key):
                if key not in cache:
                    cache[key] = METHODS[key].fit(dataset, delta=delta)
            comparison = metrics.agreement.compare(
                cache[a_key], cache[b_key], dataset=dataset)
            row.update(comparison)
            row["verdict"] = metrics.agreement.verdict(comparison, (a_key, b_key))
        except Exception as exc:                  # noqa: BLE001
            row["skip_reason"] = f"{type(exc).__name__}: {exc}"
        rows.append(row)
    return rows


def _write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    # Union of keys: cells legitimately produce different columns (a dataset without
    # an inf-sup input has no beta columns), and a fixed header would drop them.
    fields: list[str] = []
    for row in rows:
        for k in row:
            if k not in fields:
                fields.append(k)
    with path.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields, restval="")
        writer.writeheader()
        writer.writerows(rows)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="run the rb_vi_bench grid")
    p.add_argument("--datasets", nargs="*", default=list(ds_mod.FAST),
                   help=f"default: the fast tier {list(ds_mod.FAST)}")
    p.add_argument("--methods", nargs="*", default=list(DEFAULT_METHODS),
                   help="default: one canonical implementation per algorithm; "
                        f"pass names to widen (all: {sorted(METHODS)})")
    p.add_argument("--deltas", nargs="*", type=float, default=list(DEFAULT_DELTAS))
    p.add_argument("--cardinalities", nargs="*", type=int, default=list(DEFAULT_CARDINALITIES))
    p.add_argument("--subsample", type=int, default=None,
                   help="cap training snapshots (changes the numbers; recorded in output)")
    p.add_argument("--no-infsup", action="store_true")
    p.add_argument("--no-determinism", action="store_true")
    p.add_argument("--out", type=Path, default=RESULTS)
    args = p.parse_args(argv)

    started = time.perf_counter()
    grid_rows: list[dict] = []
    agree_rows: list[dict] = []

    for ds_key in args.datasets:
        t0 = time.perf_counter()
        try:
            dataset = _subsample(ds_mod.load(ds_key), args.subsample)
        except Exception as exc:                  # noqa: BLE001
            print(f"[skip] {ds_key}: {type(exc).__name__}: {exc}", file=sys.stderr)
            grid_rows.append({"dataset": ds_key, "skip_reason":
                              f"dataset build failed: {type(exc).__name__}: {exc}"})
            continue
        print(f"[{ds_key}] dim={dataset.dim} n_train={dataset.train().shape[1]} "
              f"infsup={dataset.supports_infsup} ({time.perf_counter()-t0:.1f}s to build)",
              flush=True)

        for delta in args.deltas:
            for m in args.methods:
                grid_rows.append(run_cell(
                    dataset, m, delta=delta,
                    with_infsup=not args.no_infsup,
                    with_determinism=not args.no_determinism))
            agree_rows.extend(run_agreement(dataset, delta=delta))
            print(f"  tolerance delta={delta} done ({time.perf_counter()-t0:.1f}s)", flush=True)

        for R in args.cardinalities:
            for m in args.methods:
                grid_rows.append(run_cell(
                    dataset, m, R=R,
                    with_infsup=not args.no_infsup,
                    with_determinism=not args.no_determinism))
            print(f"  cardinality R={R} done ({time.perf_counter()-t0:.1f}s)", flush=True)

        # Flush after every dataset. A full grid can run for half an hour -- the
        # tight-tolerance cells on membrane_2d alone take minutes each -- and writing
        # only at the end makes the whole run all-or-nothing against an interrupt or a
        # crash in a later dataset. The manifest is written last and is what marks a
        # run complete, so a partial results/ directory is recognisable as partial.
        args.out.mkdir(parents=True, exist_ok=True)
        _write_csv(args.out / "grid.csv", grid_rows)
        _write_csv(args.out / "agreement.csv", agree_rows)

    args.out.mkdir(parents=True, exist_ok=True)
    _write_csv(args.out / "grid.csv", grid_rows)
    _write_csv(args.out / "agreement.csv", agree_rows)

    ran = sum(1 for r in grid_rows if not r.get("skip_reason"))
    manifest = {
        "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "elapsed_seconds": round(time.perf_counter() - started, 1),
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "numpy": np.__version__,
        "datasets": args.datasets,
        "methods": args.methods,
        "deltas": args.deltas,
        "cardinalities": args.cardinalities,
        "subsample": args.subsample,
        "cells_total": len(grid_rows),
        "cells_run": ran,
        "cells_skipped": len(grid_rows) - ran,
        "agreement_rows": len(agree_rows),
    }
    (args.out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")

    print(f"\n{ran}/{len(grid_rows)} cells ran, {len(agree_rows)} agreement comparisons, "
          f"{manifest['elapsed_seconds']}s -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
