/-
# Normalized ADG: unconditional finite termination and the covering bound

`ADGRate.lean` reduces the *geometric* convergence rate of ADG to a per-step
angular-defect contraction `err (n+1) ≤ q · err n` with `q < 1`.  That per-step
contraction is a genuine hypothesis: greedy error can stall for several rounds
and then drop, so no fixed per-step factor `q` exists in general, and it is
**not** implied by a density assumption.  What finiteness and density *do* give
unconditionally is proved here.

* **Finite exact termination.**  Modelling ADG concretely as a per-round
  selection `sel n ∈ X` that, while the error is positive, always picks a
  snapshot not yet a generator (exactly what the max-angle rule does — the worst
  snapshot has positive distance to the current cone, hence is new), the
  worst-case error hits `0` after at most `|X|` rounds:
  `FiniteRun.err_eq_zero_of_card_le`.  This is the honest *unconditional* rate —
  exact recovery in finitely many rounds.

* **Covering / δ-density bound.**  Whenever the selected generators δ-cover the
  snapshot set (every snapshot within `δ` of some generator), the worst-case
  error is at most `δ`: `FiniteRun.err_le_of_cover`.  This is the correct form
  of the "δ-dense ⇒ small error" statement — a threshold bound, not a per-step
  contraction.
-/
import «Theorical proves».ADGRate

namespace ADG

open Filter Metric
open scoped Topology

-- The finite generator bookkeeping below uses `Finset.insert`/`image`, which
-- need `DecidableEq E`.  Snapshots live in a real vector space (no computable
-- equality), so we supply it classically rather than assuming it in the API.
attribute [local instance] Classical.propDecidable

/-- A concrete ADG run driven by a per-round selection `sel n ∈ X`.  The cone
after round `n` is generated by the origin together with the first `n` selected
snapshots; membership of a selected snapshot in that generating set is what makes
it exactly resolved (residual `0`). -/
structure FiniteRun (E : Type*) [NormedAddCommGroup E] where
  /-- Training snapshots. -/
  X : Finset E
  /-- The snapshot set is nonempty. -/
  hX : X.Nonempty
  /-- The snapshot selected at round `n`. -/
  sel : ℕ → E
  /-- Every selected snapshot is one of the training snapshots. -/
  sel_mem : ∀ n, sel n ∈ X

namespace FiniteRun

variable {E : Type*} [NormedAddCommGroup E] (F : FiniteRun E)

/-- Generators after `n` rounds: the origin together with the first `n` picks. -/
noncomputable def gens (n : ℕ) : Finset E := insert 0 ((Finset.range n).image F.sel)

/-- The positive cone (as a set) after `n` rounds. -/
noncomputable def K (n : ℕ) : Set E := ↑(F.gens n)

lemma zero_mem_gens (n : ℕ) : (0 : E) ∈ F.gens n := Finset.mem_insert_self _ _

lemma zero_mem_K (n : ℕ) : (0 : E) ∈ F.K n := Finset.mem_coe.2 (F.zero_mem_gens n)

/-- One round adds exactly the new pick to the generating set. -/
lemma gens_succ (n : ℕ) : F.gens (n + 1) = insert (F.sel n) (F.gens n) := by
  unfold gens
  rw [Finset.range_add_one, Finset.image_insert, Finset.insert_comm]

lemma gens_subset_succ (n : ℕ) : F.gens n ⊆ F.gens (n + 1) := by
  rw [F.gens_succ]; exact Finset.subset_insert _ _

lemma nested (n : ℕ) : F.K n ⊆ F.K (n + 1) :=
  Finset.coe_subset.2 (F.gens_subset_succ n)

lemma sel_mem_gens_succ (n : ℕ) : F.sel n ∈ F.gens (n + 1) := by
  rw [F.gens_succ]; exact Finset.mem_insert_self _ _

/-- The generating set never has more than `|X| + 1` elements (the `+1` is the
origin). -/
lemma gens_card_le (n : ℕ) : (F.gens n).card ≤ F.X.card + 1 := by
  have himg : (Finset.range n).image F.sel ⊆ F.X := by
    rw [Finset.image_subset_iff]
    intro k _; exact F.sel_mem k
  calc
    (F.gens n).card ≤ ((Finset.range n).image F.sel).card + 1 := Finset.card_insert_le _ _
    _ ≤ F.X.card + 1 := Nat.add_le_add_right (Finset.card_le_card himg) 1

/-- Adding a genuinely new pick increases the generator count by one. -/
lemma gens_card_succ_of_new {n : ℕ} (h : F.sel n ∉ F.gens n) :
    (F.gens (n + 1)).card = (F.gens n).card + 1 := by
  rw [F.gens_succ, Finset.card_insert_of_notMem h]

/-- The worst-case (per-snapshot) residual after round `n`. -/
noncomputable def err (n : ℕ) : ℝ := worstError F.X F.hX (F.K n)

lemma err_nonneg (n : ℕ) : 0 ≤ F.err n := worstError_nonneg _ _ _

lemma err_antitone : Antitone F.err := by
  refine antitone_nat_of_succ_le (fun n => ?_)
  exact worstError_antitone F.hX ⟨0, F.zero_mem_K n⟩ (F.nested n)

/-- **Progress ⇒ growth.**  While the error is positive the greedy pick is new
(the max-angle snapshot has positive distance to the cone), so the generator
count grows: after `n` such rounds there are at least `n + 2` generators. -/
lemma card_ge_of_pos (hprog : ∀ n, 0 < F.err n → F.sel n ∉ F.gens n) :
    ∀ n, (∀ k, k ≤ n → 0 < F.err k) → n + 2 ≤ (F.gens (n + 1)).card := by
  intro n
  induction n with
  | zero =>
    intro hpos
    have h0 : F.sel 0 ∉ F.gens 0 := hprog 0 (hpos 0 (le_refl 0))
    have hc : (F.gens (0 + 1)).card = (F.gens 0).card + 1 := F.gens_card_succ_of_new h0
    have hg0 : (F.gens 0).card = 1 := by simp [gens]
    omega
  | succ n ih =>
    intro hpos
    have hn : ∀ k, k ≤ n → 0 < F.err k := fun k hk => hpos k (le_trans hk (Nat.le_succ n))
    have ihc : n + 2 ≤ (F.gens (n + 1)).card := ih hn
    have hnew : F.sel (n + 1) ∉ F.gens (n + 1) := hprog (n + 1) (hpos (n + 1) (le_refl _))
    have hc : (F.gens (n + 1 + 1)).card = (F.gens (n + 1)).card + 1 :=
      F.gens_card_succ_of_new hnew
    omega

/-- **Finite exact termination (unconditional rate).**  Under the greedy-progress
hypothesis, the worst-case error is exactly `0` once `n` reaches `|X|`: ADG
recovers every snapshot in at most `|X|` rounds. -/
theorem err_eq_zero_of_card_le (hprog : ∀ n, 0 < F.err n → F.sel n ∉ F.gens n)
    {n : ℕ} (hn : F.X.card ≤ n) : F.err n = 0 := by
  have key : F.err F.X.card = 0 := by
    by_contra hne
    have hpos0 : 0 < F.err F.X.card := lt_of_le_of_ne (F.err_nonneg _) (Ne.symm hne)
    have hall : ∀ k, k ≤ F.X.card → 0 < F.err k := fun k hk =>
      lt_of_lt_of_le hpos0 (F.err_antitone hk)
    have hcard := F.card_ge_of_pos hprog F.X.card hall
    have hle := F.gens_card_le (F.X.card + 1)
    omega
  have hmono : F.err n ≤ F.err F.X.card := F.err_antitone hn
  rw [key] at hmono
  exact le_antisymm hmono (F.err_nonneg n)

/-- **Convergence, restated.**  The worst-case error is eventually `0`, hence
tends to `0`. -/
theorem tendsto_zero (hprog : ∀ n, 0 < F.err n → F.sel n ∉ F.gens n) :
    Tendsto F.err atTop (𝓝 0) := by
  refine tendsto_atTop_of_eventually_const (i₀ := F.X.card) ?_
  intro n hn
  exact F.err_eq_zero_of_card_le hprog hn

/-- **Covering / δ-density bound.**  If the generators after round `n` δ-cover the
snapshot set — every snapshot lies within `δ` of some generator — then the
worst-case error is at most `δ`.  This is the honest form of "δ-dense ⇒ small
error": a threshold bound reached once the cone's generators are dense enough. -/
theorem err_le_of_cover {n : ℕ} {δ : ℝ}
    (hcov : ∀ x ∈ F.X, ∃ g ∈ F.gens n, dist x g ≤ δ) : F.err n ≤ δ := by
  show F.X.sup' F.hX (fun x => coneResidual x (F.K n)) ≤ δ
  refine Finset.sup'_le F.hX _ (fun x hx => ?_)
  obtain ⟨g, hg, hgd⟩ := hcov x hx
  have h1 : coneResidual x (F.K n) ≤ dist x g :=
    Metric.infDist_le_dist_of_mem (Finset.mem_coe.2 hg)
  exact le_trans h1 hgd

end FiniteRun

end ADG
